// Centralized registration of all WepSIM custom elements
// No more module-level side effects — call registerWebComponents() during bootstrap

import { register_uielto } from './wepsim_uielto.js';

import { ws_about } from './wepsim_uielto_about.js';
import { ws_bin_asm } from './wepsim_uielto_bin_asm.js';
import { ws_bin_mc } from './wepsim_uielto_bin_mc.js';
import { ws_cachememory } from './wepsim_uielto_cache.js';
import { ws_cache_config } from './wepsim_uielto_cache_config.js';
import { ws_compilationbar } from './wepsim_uielto_compilationbar.js';
import { ws_config } from './wepsim_uielto_index_config.js';
import { ws_console } from './wepsim_uielto_console.js';
import { ws_cpu } from './wepsim_uielto_cpu.js';
import { ws_cpucu_got } from './wepsim_uipacker_cpu_cu.js';
import { ws_cpusvg } from './wepsim_uielto_cpusvg.js';
import { ws_ctoasm } from './wepsim_uipacker_cto_asm.js';
import { ws_dbg_mc } from './wepsim_uielto_dbg_mc.js';
import { ws_dbg_mp } from './wepsim_uielto_dbg_asm.js';
import { ws_ddown_info } from './wepsim_uipacker_ddown_info.js';
import { ws_ddown_sel } from './wepsim_uipacker_ddown_sel.js';
import { ws_edit_as } from './wepsim_uielto_editas.js';
import { ws_edit_mc } from './wepsim_uielto_editmc.js';
import { ws_executionbar } from './wepsim_uielto_executionbar.js';
import { ws_examples } from './wepsim_uielto_index_examples.js';
import { ws_flash_asm } from './wepsim_uielto_flash_asm.js';
import { ws_flash_fpga } from './wepsim_uielto_flash_fpga.js';
import { ws_help } from './wepsim_uielto_index_help.js';
import { ws_help_hweltos } from './wepsim_uielto_help_hweltos.js';
import { ws_help_swset } from './wepsim_uielto_help_swset.js';
import { ws_hw } from './wepsim_uielto_hw.js';
import { ws_io_config } from './wepsim_uielto_timer_config.js';
import { ws_io_info } from './wepsim_uielto_timer_info.js';
import { ws_l3d } from './wepsim_uielto_l3d.js';
import { ws_ledm } from './wepsim_uielto_ldm.js';
import { ws_list_cfg } from './wepsim_uielto_listcfg.js';
import { ws_list_example } from './wepsim_uielto_listexample.js';
import { ws_list_processor } from './wepsim_uielto_listprocessor.js';
import { ws_load_file } from './wepsim_uielto_loadfile.js';
import { ws_load_link } from './wepsim_uielto_loadlink.js';
import { ws_mainmemory } from './wepsim_uielto_mem.js';
import { ws_mem_config } from './wepsim_uielto_mem_config.js';
import { ws_notifications } from './wepsim_uielto_notifications.js';
import { ws_recordbar } from './wepsim_uielto_recordbar.js';
import { ws_registers } from './wepsim_uielto_registers.js';
import { ws_save_file } from './wepsim_uielto_savefile.js';
import { ws_save_files } from './wepsim_uielto_savefiles.js';
import { ws_save_files_option } from './wepsim_uielto_savefiles.js';
import { ws_segments } from './wepsim_uielto_segments.js';
import { ws_share_link } from './wepsim_uielto_sharelink.js';
import { ws_simmicasm } from './wepsim_uipacker_sim_mic_asm.js';
import { ws_slider_cpucu } from './wepsim_uielto_slider_cpucu.js';
import { ws_slider_details } from './wepsim_uielto_slider_details.js';
import { ws_sound } from './wepsim_uielto_sound.js';
import { ws_states } from './wepsim_uielto_states.js';
import { ws_toolbar } from './wepsim_uielto_toolbar.js';
import { ws_topbar } from './wepsim_uielto_topbar.js';
import { ws_uiscreen_classic } from './wepsim_uiscreen_classic.js';
import { ws_uiscreen_compact } from './wepsim_uiscreen_compact.js';
import { ws_web_main } from './wepsim_uiscreen_main.js';

export function wepsim_web_register_components()
{
    register_uielto('ws-about', ws_about);
    register_uielto('ws-bin-asm', ws_bin_asm);
    register_uielto('ws-bin-mc', ws_bin_mc);
    register_uielto('ws-cachememory', ws_cachememory);
    register_uielto('ws-cache-config', ws_cache_config);
    register_uielto('ws-compilationbar', ws_compilationbar);
    register_uielto('ws-config', ws_config);
    register_uielto('ws-console', ws_console);
    register_uielto('ws-cpu', ws_cpu);
    register_uielto('ws-cpucu_got', ws_cpucu_got);
    register_uielto('ws-cpusvg', ws_cpusvg);
    register_uielto('ws-ctoasm', ws_ctoasm);
    register_uielto('ws-dbg-mc', ws_dbg_mc);
    register_uielto('ws-dbg-mp', ws_dbg_mp);
    register_uielto('ws-ddown-info', ws_ddown_info);
    register_uielto('ws-ddown-sel', ws_ddown_sel);
    register_uielto('ws-edit-as', ws_edit_as);
    register_uielto('ws-edit-mc', ws_edit_mc);
    register_uielto('ws-executionbar', ws_executionbar);
    register_uielto('ws-examples', ws_examples);
    register_uielto('ws-flash-asm', ws_flash_asm);
    register_uielto('ws-flash-fpga', ws_flash_fpga);
    register_uielto('ws-help', ws_help);
    register_uielto('ws-help-hweltos', ws_help_hweltos);
    register_uielto('ws-help-swset', ws_help_swset);
    register_uielto('ws-hw', ws_hw);
    register_uielto('ws-io-config', ws_io_config);
    register_uielto('ws-io-info', ws_io_info);
    register_uielto('ws-l3d', ws_l3d);
    register_uielto('ws-ledm', ws_ledm);
    register_uielto('ws-list-cfg', ws_list_cfg);
    register_uielto('ws-list-example', ws_list_example);
    register_uielto('ws-list-processor', ws_list_processor);
    register_uielto('ws-load-file', ws_load_file);
    register_uielto('ws-load-link', ws_load_link);
    register_uielto('ws-mainmemory', ws_mainmemory);
    register_uielto('ws-mem-config', ws_mem_config);
    register_uielto('ws-notifications', ws_notifications);
    register_uielto('ws-recordbar', ws_recordbar);
    register_uielto('ws-registers', ws_registers);
    register_uielto('ws-save-file', ws_save_file);
    register_uielto('ws-save-files', ws_save_files);
    register_uielto('ws-save-files-option', ws_save_files_option);
    register_uielto('ws-segments', ws_segments);
    register_uielto('ws-share-link', ws_share_link);
    register_uielto('ws-simmicasm', ws_simmicasm);
    register_uielto('ws-slider-cpucu', ws_slider_cpucu);
    register_uielto('ws-slider-details', ws_slider_details);
    register_uielto('ws-sound', ws_sound);
    register_uielto('ws-states', ws_states);
    register_uielto('ws-toolbar', ws_toolbar);
    register_uielto('ws-topbar', ws_topbar);
    register_uielto('ws-screen-classic', ws_uiscreen_classic);
    register_uielto('ws-screen-compact', ws_uiscreen_compact);
    register_uielto('ws-web-main', ws_web_main);
}
